packages:
  # Main packages needed
  rust-tonic:
    # https://github.com/hyperium/tonic
    paths: [ rust-tonic ]
    specfile_path: rust-tonic.spec
    upstream_package_name: tonic
    downstream_package_name: rust-tonic
    actions: &Actions-Package-rust2rpm
      get-current-version:
        - sh -c 'rpmspec -q --qf "%{Version}" --srpm ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
      fix-spec-file:
        - sh -c 'rust2rpm ${PACKIT_UPSTREAM_PACKAGE_NAME}'
      create-archive: &Create-archive-crate
        - sh -c 'spectool -g -s0 ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
        - sh -c 'echo ${PACKIT_UPSTREAM_PACKAGE_NAME}-${PACKIT_PROJECT_VERSION}.crate'
  rust-tonic-build:
    # https://github.com/hyperium/tonic
    paths: [ rust-tonic-build ]
    specfile_path: rust-tonic-build.spec
    upstream_package_name: tonic-build
    downstream_package_name: rust-tonic-build
    actions: *Actions-Package-rust2rpm
  rust-tonic-types:
    # https://github.com/hyperium/tonic
    paths: [ rust-tonic-types ]
    specfile_path: rust-tonic-types.spec
    upstream_package_name: tonic-types
    downstream_package_name: rust-tonic-types
    actions: *Actions-Package-rust2rpm

srpm_build_deps:
  - rust2rpm

jobs:
  - job: copr_build
    trigger: commit
    update_release: false
    targets:
      - fedora-rawhide
