packages:
  # Main packages needed
  rust-tonic:
    # https://github.com/hyperium/tonic
    paths: [ rust-tonic ]
    specfile_path: rust-tonic.spec
    upstream_package_name: tonic
    downstream_package_name: rust-tonic
    actions: &Actions-Package-rust2rpm
      get-current-version:
        - sh -c 'rpmspec -q --qf "%{Version}" --srpm ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
      fix-spec-file:
        - sh -c 'rust2rpm ${PACKIT_UPSTREAM_PACKAGE_NAME}'
      create-archive: &Create-archive-crate
        - sh -c 'spectool -g -s0 ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
        - sh -c 'echo ${PACKIT_UPSTREAM_PACKAGE_NAME}-${PACKIT_PROJECT_VERSION}.crate'
  rust-tonic-build:
    # https://github.com/hyperium/tonic
    paths: [ rust-tonic-build ]
    specfile_path: rust-tonic-build.spec
    upstream_package_name: tonic-build
    downstream_package_name: rust-tonic-build
    actions: *Actions-Package-rust2rpm
  rust-tonic-types:
    # https://github.com/hyperium/tonic
    paths: [ rust-tonic-types ]
    specfile_path: rust-tonic-types.spec
    upstream_package_name: tonic-types
    downstream_package_name: rust-tonic-types
    actions: *Actions-Package-rust2rpm

  # Missing dependencies
  rust-hyper-timeout:
    # https://github.com/hjr3/hyper-timeout
    paths: [ rust-hyper-timeout ]
    specfile_path: rust-hyper-timeout.spec
    upstream_package_name: hyper-timeout
    downstream_package_name: rust-hyper-timeout
    actions: *Actions-Package-rust2rpm

  # Update dependencies
  rust-prost:
    paths: [ rust-prost ]
    specfile_path: rust-prost.spec
    upstream_package_name: prost
    downstream_package_name: rust-prost
    actions: &Actions-Package-fix-license-files
      <<: *Actions-Package-rust2rpm
      fix-spec-file:
        - sh -c 'rust2rpm -I ${PACKIT_UPSTREAM_PACKAGE_NAME}'
        - "sh -c 'sed -i \"s/# FIXME: no license files detected/cat license_files.txt/e\" ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'"
  rust-prost-derive:
    paths: [ rust-prost-derive ]
    specfile_path: rust-prost-derive.spec
    upstream_package_name: prost-derive
    downstream_package_name: rust-prost-derive
    actions: *Actions-Package-rust2rpm
  rust-prost-build:
    paths: [ rust-prost-build ]
    specfile_path: rust-prost-build.spec
    upstream_package_name: prost-build
    downstream_package_name: rust-prost-build
    actions: *Actions-Package-rust2rpm
  rust-prost-types:
    paths: [ rust-prost-types ]
    specfile_path: rust-prost-types.spec
    upstream_package_name: prost-types
    downstream_package_name: rust-prost-types
    actions: *Actions-Package-rust2rpm

srpm_build_deps:
  - rust2rpm

jobs:
  - job: copr_build
    trigger: commit
    update_release: false
    targets:
      - fedora-rawhide
