# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate prost-build

Name:           rust-prost-build
Version:        0.12.6
Release:        %autorelease
Summary:        Generate Prost annotated Rust types from Protocol Buffers files

License:        Apache-2.0
URL:            https://crates.io/crates/prost-build
Source:         %{crates_source}

BuildRequires:  cargo-rpm-macros >= 24
BuildRequires:  protobuf-compiler

%global _description %{expand:
Generate Prost annotated Rust types from Protocol Buffers files.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch
Requires:       protobuf-compiler

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+cleanup-markdown-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+cleanup-markdown-devel %{_description}

This package contains library source intended for building other packages which
use the "cleanup-markdown" feature of the "%{crate}" crate.

%files       -n %{name}+cleanup-markdown-devel
%ghost %{crate_instdir}/Cargo.toml

%package     -n %{name}+format-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+format-devel %{_description}

This package contains library source intended for building other packages which
use the "format" feature of the "%{crate}" crate.

%files       -n %{name}+format-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
