[scripts.prep]
pre = ["cp -p '%{SOURCE10}' ."]
post = [
    "# Do not depend on criterion; it is needed only for benchmarks.",
    "tomcli set Cargo.toml del dev-dependencies.criterion",
]

[requires]
build = [
    "tomcli",
]

[[package.extra-sources]]
number = 10
file = "https://github.com/tokio-rs/prost/raw/v%{version}/LICENSE"
comments = [
    "Fix missing LICENSE file in released crates",
    "https://github.com/tokio-rs/prost/issues/1085",
]
